version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPass123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/opt/mssql/data/master.mdf"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  backend:
    image: hrflow-backend:latest 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=MonAppDb;User Id=sa;Password=YourPass123!;TrustServerCertificate=True;
    ports:
      - "5000:5000"
    volumes:
      - backend_wwwroot:/app/wwwroot
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      placement:
        constraints:
          - node.role == manager

  frontend:
    image: hrflow-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 128M
      placement:
        constraints:
          - node.role == manager

volumes:
  sqlserver_data:
  backend_wwwroot:

networks:
  app-network:
    driver: overlay
